language: python
python: 3.7
services:
- docker
before-install:
- cd data-retrieval
install:
- pip3 install -r requirements.txt
script:
- python3 dataretrieval_test.py 
- echo "Succesfully ran Test cases for Data retrieval services"
after-success:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- export REPO=nibafna/data-retrieval
- export TAG=`if [ "$TRAVIS_BRANCH" == "feature/data-retrieval" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- docker build -t data-retrieval .
- docker tag data-retrieval $REPO:$TAG
- docker push $REPO:$TAG
branches:
only:
- feature/data-retrieval
