language: python
python: 3.7
services:
- docker
before-install:
- cd postprocessing
install:
- pip3 install -r requirements.txt
script:
- echo "Insert test cases here"
after-success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io
  - export REPO=nibafna/post-process
  - export TAG=`if [ "$TRAVIS_BRANCH" == "feature/post-processing" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t post-process .
  - docker tag post-process $REPO:$TAG
  - docker push $REPO:$TAG
branches:
only:
- feature/post-processing
