language: java
jdk:
  - oraclejdk13
before-script:
  - cd user_management
script:
#  - mvn -Dmaven.test.skip test-compile jar:test-jar install
  - echo "Insert Test case here"
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export REPO=nibafna/user-management
  - export TAG=latest
  - docker build -t user-management .
  - docker tag user-management $REPO:$TAG
  - docker push $REPO:$TAG
  - cd ../
  - chmod 600 cloud-key
  - eval "$(ssh-agent -s)"
  - ssh -o StrictHostKeyChecking=no -i cloud-key ubuntu@149.165.170.202 pwd
  - ssh -i cloud-key ubuntu@149.165.170.202 ./deploy_usermgmt.sh
branches:
  only:
  - feature/user-management
