language: python
python: 3.7
services:
- docker
before-install:
- cd data-retrieval
install:
- pip3 install -r requirements.txt
script:
- python3 dataretrieval_test.py 
- echo "Succesfully ran Test cases for Data retrieval services"
after-success:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker build -t nsa/data-retrieval:latest .
- docker tag nsa/data-retrieval $DOCKER_USER/nsa/data-retrieval:latest
- docker push $DOCKER_USER/nsa/data-retrieval:latest
branches:
only:
- feature/data-retrieval
