language: node_js
sudo: false
node_js: 10.16
cache:
  directories:
    - "node_modules"
before-install:
  - cd session-management
install:
  - npm install --check-files
script: 
#  - npm start
  - echo "Insert tests here - session management"
after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export REPO=nibafna/session-management
  - export TAG=`if [ "$TRAVIS_BRANCH" == "feature/session-management" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t session-management .
  - docker tag session-management $REPO:$TAG
  - docker push $REPO:$TAG
branches:
  only:
  - feature/session-management
