language: python
python: 3.7
services:
- docker
before-install:
- cd postprocessing
install:
- pip3 install -r requirements.txt
script:
- echo "Insert test cases here"
after-success:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- export REPO=nibafna/post-processing
- export TAG=`if [ "$TRAVIS_BRANCH" == "feature/post-processing" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- docker build -t post-processing .
- docker tag post-processing $REPO:$TAG
- docker push $REPO:$TAG
branches:
only:
- feature/post-processing
