language: python
python: 3.7
services:
- docker
before-install:
- cd data-retrieval
install:
- pip3 install -r requirements.txt
script:
- python3 dataretrieval_test.py 
after-success:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker build -t nsa/data-retrieval:latest .
- docker push nsa/data-retrieval:latest
branches:
only:
- feature/data-retrieval
