language: python
python: 3.7
services:
- docker
before-install:
- cd postprocessing
install:
- pip3 install -r requirements.txt
script:
- echo "Insert test cases here"
after-success:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker build -t nsa/postprocessing:latest .
- docker push nsa/postprocessing:latest
branches:
only:
- feature/post-processing