apiVersion: v1
kind: Service
metadata:
  name: adminer-service
spec:
 type: LoadBalancer
 ports:
  - targetPort: 8083
    port: 8083
    nodePort: 31083
 selector:
  app: adminer-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-deployment
spec:
  selector:
    matchLabels:
      app: adminer-pod
  replicas: 1 
  template:
    metadata:
      labels:
        app: adminer-pod
    spec:
      containers:
      - name: adminer-container
        image: adminer
        ports:
        - containerPort: 8083

