apiVersion: v1
kind: Service
metadata:
  name: api
spec:
 type: LoadBalancer
 ports:
  - name: "8081"
    port: 8081
    nodePort: 32450
    targetPort: 8081
 selector:
  app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
   app: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 5
  strategy:
   type: Recreate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        imagePullPolicy: Always
        image: nibafna/api-gateway:latest
        ports:
        - containerPort: 8081
      restartPolicy: Always

