apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
 type: LoadBalancer
 ports:
  - targetPort: 3000
    port: 3000
    nodePort: 31001
 selector:
  app: ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  selector:
    matchLabels:
      app: ui
  replicas: 5 
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        imagePullPolicy: Always
        image: nibafna/user-interface:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_BACKEND_IP
          value: "$REACT_APP_BACKEND_IP"
      restartPolicy: Always
