apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
spec:
 type: LoadBalancer
 ports:
  - targetPort: 8081
    port: 8081
    nodePort: 31002
 selector:
  app: api-gateway-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
spec:
  selector:
    matchLabels:
      app: api-gateway-pod
  replicas: 3
  strategy: 
   type: Recreate
  template:
    metadata:
      labels:
        app: api-gateway-pod
    spec:
      containers:
      - name: api-gateway-container
        imagePullPolicy: Always
        image: nibafna/api-gateway
        ports:
        - containerPort: 8081
      restartPolicy: Always

