apiVersion: v1
kind: Service
metadata:
  name: user-interface-service
spec:
 type: LoadBalancer
 ports:
  - targetPort: 3000
    port: 3000
    nodePort: 31001
 selector:
  app: user-interface-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-interface-deployment
spec:
  selector:
    matchLabels:
      app: user-interface-pod
  replicas: 3
  strategy: 
   type: Recreate
  template:
    metadata:
      labels:
        app: user-interface-pod
    spec:
      containers:
      - name: user-interface-container
        imagePullPolicy: Always
        image: nibafna/user-interface
        ports:
        - containerPort: 3000
      restartPolicy: Always





